version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: eventbus-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server
    volumes:
      - redis_data:/data

volumes:
  redis_data:
